[package]
name = "blimey"
version = "0.1.0"
authors = ["Nathan Lilienthal <nathan@nixpulvis.com>"]

[lib]
proc_macro = true

[dependencies]
syn = { version = "*", features = ["full", "fold"] }
quote = "*"

